version: '3.8'

services:
  app:
    build: .
    container_name: heartguard-app
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: heartguard-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
